Entertainer.create(username: "jonopens", job_type: "Magician", image: 'http://media.gettyimages.com/photos/1960s-man-magician-wearing-picture-id563941525', rate: '25', description: 'so much magic. so much watermark.', password: "password")
Entertainer.create(username: "ianramos", job_type: "Animal Tamer", image: 'https://openclipart.org/image/2400px/svg_to_png/218951/animaltrainer.png', rate: '25', description: 'I can tame lions n stuff.', password: "password")
Entertainer.create(username: "ryansperzel", job_type: "Clown", image: 'http://s.hswstatic.com/gif/how-clowns-work-orig.jpg', rate: '25', description: 'balloon animals are sweet.', password: "password")
Entertainer.create(username: "asheaust", job_type: "Magician", image: 'https://avatars.githubusercontent.com/u/27021764', rate: '50', description: 'watch me split this keyboard in half!', password: "password")
Entertainer.create(username: "shawdoot", job_type: "Musician", image: 'https://media.licdn.com/media/AAIA_wDGAAAAAQAAAAAAAAp9AAAAJDFlMDUyODc5LThhOWItNGJkMi04YzVjLWJhYWFjZDZlYTA4ZQ.jpg', rate: '40', description: 'doot', password: "password")
Entertainer.create(username: "SlaveLeia", job_type: "Belly Dancer", image: 'https://amazingstoriesmag.com/wp-content/uploads/2015/11/Rare-Slave-Leia-Images-star-wars-35052856-2276-2880.jpg', rate: '100', description: "i'm your sister", password: "password")
Entertainer.create(username: "christinap", job_type: "Mime", image: 'http://cf.ltkcdn.net/makeup/images/std/216283-675x450-Portrait-of-a-woman-mime.jpg', rate: '25', description: '...', password: "password")
Entertainer.create(username: "danielleb", job_type: "Caricature Artist", image: 'http://jkexpressions.com/wp-content/themes/JKExpressions/imgs/julia.png', rate: '25', description: 'award winning caricaturist and artist.', password: "password")
Entertainer.create(username: "davesquires", job_type: "Human Statue", image: 'http://i.dailymail.co.uk/i/pix/2014/12/10/23EA9C0500000578-0-image-a-11_1418251188483.jpg', rate: '35', description: '...', password: "password")
Host.create(username: "spiderman", password: "password", image: 'https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png')
Host.create(username: "green-goblin", password: "password", image: 'https://upload.wikimedia.org/wikipedia/en/f/fe/Green_Goblin.png')
Host.create(username: "venom", password: "password", image: 'http://vignette2.wikia.nocookie.net/marveldatabase/images/7/76/Lee_Price_%28Earth-616%29_from_Venom_Vol_3_1_003.png/revision/latest?cb=20161123180005')
Host.create(username: "queen's butler", password: "password", image: 'http://i.dailymail.co.uk/i/pix/2012/03/21/article-2118499-124625A7000005DC-69_306x423.jpg')
Host.create(username: "bored guy", password: "password", image: 'https://assets.rbl.ms/11015782/980x.gif')
Event.create(name: "Old guys playing bocce", description: "It's old guys playing bocce.", host_id: 1, date: Time.now, duration: "4.5", city: "New York", state: "NY")
Event.create(name: "Nerds reading comics", description: "It's nerds reading comics.", host_id: 3, date: Time.now, duration: "3", city: "Boston", state: "MA")
Event.create(name: "Hanging with Mr. Cooper", description: "Mark Curry is a genius, and his sitcom is a piece of timeless art.", host_id: 2, date: Time.now, duration: "6", city: "Oakland", state: "CA")
Event.create(name: "Coronation of the Queen", description: "It baffles me why we are inviting the commoners to perform, but Her Ladyship requires it. Therefore, I comply.", host_id: 4, date: Time.now, duration: "3", city: "Queens", state: "New York")
Event.create(name: "Hanging (lol) w. friends", description: "I'm a spiderman, so this was a very clever joke hahahhaha omg my sides", host_id: 1, date: Time.now, duration: "2", city: "Detroit", state: "MI")
Event.create(name: "Be bored in the country", description: "The town has a gas station, a church, a bar, and an ammo store. There's a good time in there somewhere", host_id: 5, date: Time.now, duration: "10.5", city: "Lake George", state: "MN")
Event.create(name: "Cowboy festival", description: "Yeeeeehaw.", host_id: 4, date: Time.now, duration: "8", city: "Austin", state: "TX")
Event.create(name: "Bugs Bunny convention", description: "Eh, what's up, doc?", host_id: 3, date: Time.now, duration: "5", city: "Walla Walla", state: "WA")
Event.create(name: "Desert art party", description: "The art gets pretty sandy.", host_id: 5, date: Time.now, duration: "5.5", city: "Albuquerque", state: "NM")
EventsEntertainer.create(event_id: 1, entertainer_id: 3)
EventsEntertainer.create(event_id: 1, entertainer_id: 5)
EventsEntertainer.create(event_id: 1, entertainer_id: 1)
EventsEntertainer.create(event_id: 2, entertainer_id: 3)
EventsEntertainer.create(event_id: 2, entertainer_id: 2)
EventsEntertainer.create(event_id: 2, entertainer_id: 4)
EventsEntertainer.create(event_id: 3, entertainer_id: 3)
EventsEntertainer.create(event_id: 3, entertainer_id: 2)
EventsEntertainer.create(event_id: 4, entertainer_id: 4)
EventsEntertainer.create(event_id: 4, entertainer_id: 3)
EventsEntertainer.create(event_id: 5, entertainer_id: 1)
EventsEntertainer.create(event_id: 5, entertainer_id: 5)
EventsEntertainer.create(event_id: 6, entertainer_id: 9)
EventsEntertainer.create(event_id: 7, entertainer_id: 8)
EventsEntertainer.create(event_id: 8, entertainer_id: 7)
Message.create(title:"Wanna hang out?", content:"Hey, did you wanna hangout?", host_id: 1, entertainer_id: 1, sender: "spiderman", receiver: "jonopens")
Message.create(title:"Wanna hang out?", content:"Hey, did you wanna hangout?", host_id: 1, entertainer_id: 2, sender: "spiderman", receiver: "ianramos")
Message.create(title:"Wanna hang out?", content:"Hey, did you wanna hangout?", host_id: 1, entertainer_id: 3, sender: "spiderman", receiver: "ryansperzel")
Message.create(title:"Questions", content:"Hey, I had some questions about your party", host_id: 3, entertainer_id: 1, sender: "jonopens", receiver: "venom")
Message.create(title:"Questions", content:"Hey, I had some questions about your party", host_id: 3, entertainer_id: 2, sender: "ianramos", receiver: "venom")
Message.create(title:"Questions", content:"Hey, I had some questions about your party", host_id: 3, entertainer_id: 3, sender: "ryansperzel", receiver: "venom")
